//
// Generated file, do not edit! Created by opp_msgtool 6.0 from priceQueryMsg.msg.
//

#ifndef __PRICEQUERYMSG_M_H
#define __PRICEQUERYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class priceQueryMsg;
/**
 * Class generated from <tt>priceQueryMsg.msg:33</tt> by opp_msgtool.
 * <pre>
 * packet priceQueryMsg
 * {
 *     double zValue = 0;
 *     int pathIndex = 0;
 *     bool isReversed = false;
 * }
 * </pre>
 */
class priceQueryMsg : public ::omnetpp::cPacket
{
  protected:
    double zValue = 0;
    int pathIndex = 0;
    bool isReversed_ = false;

  private:
    void copy(const priceQueryMsg& other);

  protected:
    bool operator==(const priceQueryMsg&) = delete;

  public:
    priceQueryMsg(const char *name=nullptr, short kind=0);
    priceQueryMsg(const priceQueryMsg& other);
    virtual ~priceQueryMsg();
    priceQueryMsg& operator=(const priceQueryMsg& other);
    virtual priceQueryMsg *dup() const override {return new priceQueryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getZValue() const;
    virtual void setZValue(double zValue);

    virtual int getPathIndex() const;
    virtual void setPathIndex(int pathIndex);

    virtual bool isReversed() const;
    virtual void setIsReversed(bool isReversed);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const priceQueryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, priceQueryMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline priceQueryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<priceQueryMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PRICEQUERYMSG_M_H

