//
// Generated file, do not edit! Created by opp_msgtool 6.0 from timeOutMsg.msg.
//

#ifndef __TIMEOUTMSG_M_H
#define __TIMEOUTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class timeOutMsg;
/**
 * Class generated from <tt>timeOutMsg.msg:17</tt> by opp_msgtool.
 * <pre>
 * packet timeOutMsg
 * {
 *     //double amount;
 *     int transactionId; //is messageID of transactionMsg
 *     int receiver;
 * }
 * </pre>
 */
class timeOutMsg : public ::omnetpp::cPacket
{
  protected:
    int transactionId = 0;
    int receiver = 0;

  private:
    void copy(const timeOutMsg& other);

  protected:
    bool operator==(const timeOutMsg&) = delete;

  public:
    timeOutMsg(const char *name=nullptr, short kind=0);
    timeOutMsg(const timeOutMsg& other);
    virtual ~timeOutMsg();
    timeOutMsg& operator=(const timeOutMsg& other);
    virtual timeOutMsg *dup() const override {return new timeOutMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTransactionId() const;
    virtual void setTransactionId(int transactionId);

    virtual int getReceiver() const;
    virtual void setReceiver(int receiver);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const timeOutMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, timeOutMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline timeOutMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<timeOutMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TIMEOUTMSG_M_H

